module.exports = {
  logo1: require('../theme/images/logo1.png'),
  logo2: require('../theme/images/logo2.png'),
  vitality: require('../theme/images/vitality.png'),
  mCoin: require('../theme/images/m-coin.png'),
  simple: require('../theme/images/simple.png'),
  calendar: require('../theme/images/calendar.svg'),
  location: require('../theme/images/location.svg'),
  miniTeam: require('../theme/images/mini-team.png'),
  miniTeam2: require('../theme/images/mini-team2.png'),
  miniTeam3: require('../theme/images/mini-team3.png'),
  miniTeam4: require('../theme/images/mini-team4.png'),
  money: require('../theme/images/money.svg'),
  teams: require('../theme/images/teams.svg'),
  dust: require('../theme/images/dust.png'),
  nuke: require('../theme/images/nuke.jpg'),
  inferno: require('../theme/images/inferno.jpg'),
  player1: require('../theme/images/player1.png'),
  player2: require('../theme/images/player2.png'),
  player3: require('../theme/images/player3.png'),
  player4: require('../theme/images/player4.png'),
  player5: require('../theme/images/player5.png'),
  ru: require('../theme/images/ru.png'),
  ua: require('../theme/images/ua.png'),

}
